name: FST tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Get some info
        run: |
          pwd
          ls -la
          echo "# df -h" && df -h

      - name: Checkout (Get codes)
        uses: actions/checkout@v2

      - name: Get some info
        run: |
          pwd
          ls -la

      - name: Run unittests
        run: python3 -m unittest discover -v -s "./tests" -p "test*.py"

  build-and-publish-testpypi:
    runs-on: ubuntu-20.04
    needs: run-tests
    if: always()
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade build setuptools wheel

    - name: Build
      run: |
        NEWTESTPYPIVER=$(./util/get_last_ver_from_pypi.sh SciPyFST).dev$(date +%Y%m%d%H%M%S)
        echo $NEWTESTPYPIVER
        sed -i "s/NEWSciPyFSTVERSION/$NEWTESTPYPIVER/g" setup.cfg
        python -m build .

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: github.event_name == 'push'
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_KEY }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
        verbose: true
