name: Release to Test PyPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade build setuptools wheel

    - name: Build
      run: |
        NEWTESTPYPIVER=$(./util/get_last_ver_from_pypi.sh SciPyFST)-$(date +%Y%m%d)-${{ github.sha }}
        echo $NEWTESTPYPIVER
        sed -i "s/NEWSciPyFSTVERSION/$NEWTESTPYPIVER/g" setup.cfg
        python -m build .

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: false
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_KEY }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
        verbose: true
